version: '0'
services:
  web:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=http://localhost:4200
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4200:4200"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      
  redis:
    image: "redis"
